name: Deploy to EKS

on:
  push:
    branches:
      - main  # Modify this according to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: <your-aws-region>

    - name: Build and push Docker image
      run: |
        docker build -t your-image-name .
        docker tag your-image-name:latest your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-image-name:latest
        aws ecr get-login-password --region your-aws-region | docker login --username AWS --password-stdin your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com
        docker push your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-image-name:latest

    - name: Update Kubernetes deployment
      run: |
        kubectl apply -f path/to/kubernetes-deployment.yaml
