# monitoring.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-api-monitor
  namespace: your-namespace
spec:
  selector:
    matchLabels:
      app: my-api
  endpoints:
  - port: http
    interval: 10s
